export * from "./Home/Home";
export * from "./Productos/Productos";
export * from "./Contacto/Contacto";
export * from "./SobreNosotros/Sobrenosotros";
export * from "./ProductoDetail/ProductoDetail";
export * from "./Failure/Failure";
export * from "./Succees/Success";
export * from "./Pending/Pending";
export * from "./AdminPanel/PanelAdmin";
